// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAvRl_hkVldLr5iu7nr_ZfKlxlvlZzivU',
    appId: '1:228301483072:web:d8ef794128a051de61c3a5',
    messagingSenderId: '228301483072',
    projectId: 'facebook-clone-86509',
    authDomain: 'facebook-clone-86509.firebaseapp.com',
    storageBucket: 'facebook-clone-86509.firebasestorage.app',
    measurementId: 'G-Q91GZX2S52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlvmK69jy5p9TKRnnKL3VIYoXGiC5yxDU',
    appId: '1:813971662065:android:4f658ef0bb61e192dfb550',
    messagingSenderId: '813971662065',
    projectId: 'my-new-fb-project-aa9e0',
    storageBucket: 'my-new-fb-project-aa9e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAycikO9dMLaM3GDv1IQVVXN6d21kWZ7mc',
    appId: '1:228301483072:ios:fc182837a25dc25a61c3a5',
    messagingSenderId: '813971662065',
    projectId: 'my-new-fb-project-aa9e0',
    storageBucket: 'my-new-fb-project-aa9e0.firebasestorage.app',
    iosClientId: '228301483072-4uv0tkqn2qvhsgn8gif5hnok2jnn0h00.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAycikO9dMLaM3GDv1IQVVXN6d21kWZ7mc',
    appId: '1:228301483072:ios:fc182837a25dc25a61c3a5',
    messagingSenderId: '813971662065',
    projectId: 'my-new-fb-project-aa9e0',
    storageBucket: 'my-new-fb-project-aa9e0.firebasestorage.app',
    iosClientId: '228301483072-4uv0tkqn2qvhsgn8gif5hnok2jnn0h00.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAvRl_hkVldLr5iu7nr_ZfKlxlvlZzivU',
    appId: '1:228301483072:web:0c8f26cf2f5e3a0561c3a5',
    messagingSenderId: '813971662065',
    projectId: 'my-new-fb-project-aa9e0',
    authDomain: 'my-new-fb-project-aa9e0.firebaseapp.com',
    storageBucket: 'my-new-fb-project-aa9e0.firebasestorage.app',
    measurementId: 'G-QZHC147N5R',
  );
}